openapi: 3.0.0
info:
  title: JDIS wish 2 API
  description: API for JDIS wish 2
  version: 1.0.0
servers:
    - url: http://localhost:8080
      description: Local server
tags:
  - name: Bot
    description: Bot operations
  - name: Scoreboard
    description: Scoreboard operations
  - name: Game
    description: Game operations
paths:
  /api/bot:
    get:
      tags:
        - Bot
      summary: Get all bots
      security: []
      responses:
        200:
          description: OK

    post:
      tags:
        - Bot
      summary: Create a new bot and return its uid
      security: []
      parameters:
        - name: botName
          in: query
          required: true
          schema:
            type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                    example: "123ABC"

  /api/scoreboard:
    get:
      tags:
        - Scoreboard
      summary: Get scoreboard
      security: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Scoreboard'

  /api/game:
    get:
      tags:
        - Game
      summary: Get parameters for the current game
      security: []
      parameters:
        - name: id
          in: path
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameters:
                    $ref: '#/components/schemas/Parameters'
        404:
          description: User Not Found
        401:
          description: Unauthorized
        403:
            description: Forbidden
    put:
        tags:
            - Game
        summary: Update parameters for the current game
        security:
            - auth: [admin]
        parameters:
            - name: id
              in: path
              required: true
            - name: parameters
              in: query
              required: true
              schema:
                $ref: '#/components/schemas/Parameters'
        responses:
            200:
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      parameters:
                        $ref: '#/components/schemas/Parameters'
            404:
              description: User Not Found
            401:
              description: Unauthorized
            403:
                description: Forbidden
  /api/start:
    post:
      tags:
        - Game
      summary: Start game
      security:
        - auth: [admin]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "Game started"
        401:
          description: Unauthorized
        403:
            description: Forbidden
        409:
            description: Game already started
  /api/stop:
    post:
      tags:
        - Game
      summary: Stop game
      security:
        - auth: [admin]
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: "Game stopped"
        401:
          description: Unauthorized
        403:
            description: Forbidden
        409:
            description: No Game started
components:
  schemas:
    Scoreboard:
        type: object
        properties:
          id:
              type: integer
          name:
              type: string
          score:
              type: integer
    Parameters:
        type: object
        properties:
          map_length:
              type: integer
          soldier_speed:
              type: integer
          soldier_creation_speed:
              type: integer
          terrain_change_speed:
              type: integer
          game_length:
              type: integer
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT